FROM varnish:7-alpine

COPY dockerfiles/config/varnish-default.vcl /etc/varnish/default.vcl

RUN chmod 644 /etc/varnish/default.vcl

EXPOSE 80

# Run with custom config
CMD ["varnishd", "-f", "/etc/varnish/default.vcl", "-a", "0.0.0.0:80", "-T", "localhost:6082", "-s", "malloc,256m"]
